name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: cmake create build
      run: cmake -S . -B build
    - name: cmake build
      run: cmake --build build/ --target all
    - name: test
      run: ./build/TestInterval

  
  build-windows:

    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: cmake create project
      run: cmake -S . -B build -G "Visual Studio 17 2022" -A x64
    - name: cmake make
      run: cmake --build build --config Release
    - name: test
      run: ./build/Release/TestInterval.exe
      
    
