name: macOS

on:
  push:
    branches: 
      - '*'
  pull_request:
    branches: 
      - '*'

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: install directed-rounding dependencies
      run: brew install mpfr
    - name: create cmake project
      run: cmake -DNOTIDY=ON -DCMAKE_PREFIX_PATH="$(brew --prefix)" -B build -S .
    - name: build cmake project
      run: cmake --build build/ --target all
    - name: execute tests
      run: ctest --test-dir build --output-on-failure
