name: Windows

on:
  push:
    branches: 
      - '*'
  pull_request:
    branches: 
      - '*'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: install directed-rounding dependencies
      run: '& "$env:VCPKG_INSTALLATION_ROOT/vcpkg.exe" install mpfr:x64-windows'
    - name: create cmake project
      run: cmake -S . -B build -A x64 -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake" -DVCPKG_TARGET_TRIPLET=x64-windows
    - name: build project
      run: cmake --build build --config Debug
    - name: execute tests
      run: ctest --test-dir build -C Debug --output-on-failure
